 version: 0.2
 phases:
    install:
      commands:
        - echo Entered the Installation phase
    pre_build:
      commands:
        - echo Logging in to Amazon ECR...
        - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 066747756520.dkr.ecr.ap-south-1.amazonaws.com
    build:
      commands:
       - echo Build started on `date`
       - cd frontend
       - ls -l
       - echo Building the Docker image...          
       - docker build -t reactapp-repo -t reactapp-repo:$CODEBUILD_BUILD_NUMBER .
       - docker tag reactapp-repo:latest 066747756520.dkr.ecr.ap-south-1.amazonaws.com/reactapp-repo:latest
       - docker tag reactapp-repo:$CODEBUILD_BUILD_NUMBER 066747756520.dkr.ecr.ap-south-1.amazonaws.com/reactapp-repo:$CODEBUILD_BUILD_NUMBER
    post_build:
      commands:
       - echo Build completed on `date`
       - echo Pushing the Docker image...
       - docker push 066747756520.dkr.ecr.ap-south-1.amazonaws.com/reactapp-repo:latest
       - docker push 066747756520.dkr.ecr.ap-south-1.amazonaws.com/reactapp-repo:$CODEBUILD_BUILD_NUMBER
 