 version: 0.2
 phases:
    install:
      commands:
        - echo Entered the Installation phase
    pre_build:
      commands:
        - echo Logging in to Amazon ECR...
        - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ecr_repo_api
    build:
      commands:
       - echo Build started on `date`
       - cd backend
       - ls -l
       - echo Building the Docker image...          
       - docker build -t goapp-repo -t goapp-repo:$CODEBUILD_BUILD_NUMBER .
       - docker tag goapp-repo:latest $ecr_repo_api/goapp-repo:latest
       - docker tag goapp-repo:latest $ecr_repo_api/goapp-repo:$CODEBUILD_BUILD_NUMBER
    post_build:
      commands:
       - echo Build completed on `date`
       - echo Pushing the Docker image...
       - docker push $ecr_repo_api/goapp-repo:latest
       - docker push $ecr_repo_api/goapp-repo:$CODEBUILD_BUILD_NUMBER
    artifacts:
      files:
        - '*'
        - '**/*'
 