version: '3.8'
services:
  postgres:
    container_name: postgres_demo
    image: postgres:latest
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: admin@123
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    expose:
      - 5432
  api:
    container_name: go-app-backend
    image: 066747756520.dkr.ecr.ap-south-1.amazonaws.com/goapp-repo:latest
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - DB_HOST=postgres
      - DB_USER=super_admin
      - DB_PASSWORD=admin@123
      - DB_NAME=postgres
      - DB_PORT=5432
      - ALLOWED_ORIGINS=http://ec2-13-234-118-210.ap-south-1.compute.amazonaws.com/:3000
    links:
      - "postgres"
  react:
    container_name: frontent_api
    image: 066747756520.dkr.ecr.ap-south-1.amazonaws.com/reactapp-repo:latest
    depends_on:
      - api
    ports:
      - 3000:3000
    links:
      - "api"
volumes:
  postgres-db:
    driver: local
