name: Build and Deploy

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub or your container registry (adjust the login step based on your registry)
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t frontendapp -f fDockerfile .

    - name: tag the docker image
      run: docker tag frontendapp therafeeq/frontendapp:latest

    - name: Push Docker image
      run: docker push therafeeq/frontendapp:latest

    - name: SSH into EC2 instance and start Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          docker stop frontendapp || true
          docker rm frontendapp || true
          docker pull therafeeq/frontendapp:latest
          docker run -d -p 3000:3000 --name frontendapp therafeeq/frontendapp
